---
title: "demopkg"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{demopkg}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(firstpkg)
library(dplyr)

```

```{r demo Lorenz}
parameters <- c(a = -8/3, b = -10, c = 28)
state      <- c(X = 1, Y = 1, Z = 1)
times      <- seq(0, 100, by = 0.01)

out <- deSolve::ode(y = state, times = times, func = Lorenz, parms = parameters)

# plot(out)
# scatterplot3d::scatterplot3d(out[,-1], type = "l")

```

```{r demo GLV}
p <- 4
mu <- rep(0, p)
r0 = c(1, .72, 1.53, 1.27)
C0 = matrix(
   c(
     1,
     1.09,
     1.52,
     0,
     0,
     1,
     0.44,
     1.36,
     2.33,
     0,
     1,
     0.47,
     1.21,
     0.51,
     0.35,
     1
   ),
   p,
   p,
   byrow = TRUE
 )
parameters <- list(r = r0, s = .96, C0 = C0, mu = mu)
state      <- runif(p) %>% setNames(paste0("X", 1:p))
times      <- seq(0, 1000, by = 0.01)

out <- deSolve::ode(y = state, times = times, func = GLV, parms = parameters,
                    method = 'lsoda')
head(out)
tail(out)
nrow(out)
# plot(out)

out1 <- deSolve::ode(y = state, times = times, func = GLV, parms = parameters,
                    method = 'euler')
head(out1)
tail(out1)
nrow(out1)
# plot(out1)

out2 <- deSolve::ode(y = state, times = times, func = GLV, parms = parameters,
                    method = 'rk4')
head(out2)
tail(out2)
nrow(out2)
# plot(out2)

scatterplot3d::scatterplot3d(out[,-1], type = "l")


```


